# Generated by Django 6.0 on 2026-01-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_question_options_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='Final comments by CEO', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('SELF', 'Self Review'), ('MANAGER', 'Manager Review'), ('CEO', 'Final Review')], max_length=20),
        ),
    ]
